INSERT INTO `cse`.`location` (`Lid`, `Name`, `Resume`) VALUES ('4', '公共服务中心', '学校的大部分机关部门所在地');


INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('1', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('2', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('3', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('4', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('5', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('6', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('7', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('8', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('9', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('10', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('11', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('12', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('13', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('14', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('15', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('16', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('17', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('18', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('19', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('20', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('21', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('22', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('23', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('24', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('25', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('26', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('27', '4');
INSERT INTO `cse`.`message_location` (`Mid`, `Lid`) VALUES ('28', '4');


INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('34', '9');
INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('42', '21');
INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('43', '13');
INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('47', '21');
INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('48', '20');
INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('49', '16');
INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('50', '16');
INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('51', '16');
INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('52', '16');
INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('53', '16');
INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('56', '17');
INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('57', '17');
INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('58', '17');
INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('62', '14');
INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('65', '12');
INSERT INTO `cse`.`message_information_class` (`Mid`, `Cid`) VALUES ('64', '12');



INSERT INTO `cse`.`information_class_location` (`Cid`, `Lid`) VALUES ('19', '4');
INSERT INTO `cse`.`information_class_location` (`Cid`, `Lid`) VALUES ('20', '4');
INSERT INTO `cse`.`information_class_location` (`Cid`, `Lid`) VALUES ('21', '4');


INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('1', '1');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('1', '5');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('1', '6');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('1', '12');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('1', '16');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('1', '18');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('1', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('1', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('1', '29');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('1', '32');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('2', '1');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('2', '8');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('2', '13');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('2', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('2', '25');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('2', '27');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('2', '29');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('2', '32');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('3', '1');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('3', '8');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('3', '32');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('3', '30');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('3', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('3', '13');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('4', '13');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('4', '16');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('4', '18');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('4', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('4', '28');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('4', '32');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('5', '15');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('5', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('5', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('5', '27');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('5', '33');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('5', '31');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('9', '19');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('9', '20');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('9', '21');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('9', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('9', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('9', '24');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('9', '25');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('9', '32');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('12', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('12', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('12', '24');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('12', '25');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('12', '32');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('12', '33');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('12', '34');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('6', '14');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('6', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('6', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('6', '27');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('6', '33');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('6', '31');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('7', '13');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('7', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('7', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('7', '27');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('7', '33');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('7', '31');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('8', '14');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('8', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('8', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('8', '27');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('8', '33');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('8', '31');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('10', '13');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('10', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('10', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('10', '27');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('10', '33');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('10', '31');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('11', '14');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('11', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('11', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('11', '27');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('11', '33');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('11', '31');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('13', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('13', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('13', '24');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('13', '25');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('13', '32');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('13', '33');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('13', '34');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('14', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('14', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('14', '24');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('14', '25');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('14', '32');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('14', '33');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('14', '34');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('15', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('15', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('15', '24');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('15', '25');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('15', '32');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('15', '33');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('15', '34');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('16', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('16', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('16', '24');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('16', '25');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('16', '32');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('16', '33');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('16', '34');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('17', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('17', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('17', '24');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('17', '25');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('17', '32');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('17', '33');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('17', '34');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('18', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('18', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('18', '24');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('18', '25');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('18', '32');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('18', '33');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('18', '34');



INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('19', '19');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('19', '20');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('19', '21');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('19', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('19', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('19', '24');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('19', '25');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('19', '32');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('20', '19');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('20', '20');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('20', '21');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('20', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('20', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('20', '24');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('20', '25');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('20', '32');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('21', '19');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('21', '20');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('21', '21');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('21', '22');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('21', '23');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('21', '24');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('21', '25');
INSERT INTO `cse`.`information_class_key` (`Cid`, `Kid`) VALUES ('21', '32');

DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '1') and (`Kid` = '6');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '9') and (`Kid` = '25');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '9') and (`Kid` = '19');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '9') and (`Kid` = '20');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '9') and (`Kid` = '21');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '9') and (`Kid` = '22');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '11') and (`Kid` = '22');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '11') and (`Kid` = '23');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '12') and (`Kid` = '22');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '12') and (`Kid` = '23');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '12') and (`Kid` = '24');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '12') and (`Kid` = '25');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '13') and (`Kid` = '22');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '13') and (`Kid` = '23');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '13') and (`Kid` = '24');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '13') and (`Kid` = '25');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '14') and (`Kid` = '22');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '14') and (`Kid` = '23');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '15') and (`Kid` = '22');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '15') and (`Kid` = '23');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '16') and (`Kid` = '22');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '16') and (`Kid` = '23');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '17') and (`Kid` = '25');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '18') and (`Kid` = '22');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '18') and (`Kid` = '25');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '19') and (`Kid` = '24');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '19') and (`Kid` = '25');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '20') and (`Kid` = '20');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '20') and (`Kid` = '21');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '20') and (`Kid` = '25');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '21') and (`Kid` = '20');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '21') and (`Kid` = '21');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '21') and (`Kid` = '22');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '21') and (`Kid` = '23');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '21') and (`Kid` = '24');
DELETE FROM `cse`.`information_class_key` WHERE (`Cid` = '21') and (`Kid` = '25');
